x-microservice-common:
  &microservice-common
  build: 
    context: ./backend
  env_file:
    - .env
  environment:
    - RABBITMQ_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - REDIS_URL=redis://:redis@redis:6379/0
  volumes:
    - ./backend/keys:/app/backend/keys
  depends_on:
    rabbitmq:
      condition: service_healthy

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass redis --appendonly yes
    restart: unless-stopped

  # --- MICROSERVICES ---

  gateway:
    <<: *microservice-common
    container_name: ms-gateway
    command: python -m backend.gateway.app
    ports:
      - "5000:5000"

  promocao:
    <<: *microservice-common
    container_name: ms-promocao
    command: python -m backend.promocao

  ranking:
    <<: *microservice-common
    container_name: ms-ranking
    command: python -m backend.ranking

  notificacao:
    <<: *microservice-common
    container_name: ms-notificacao
    command: python -m backend.notificacao

volumes:
  redis-data:
    driver: local